"""change available to boolean

Revision ID: f5ad6bab5c44
Revises: 
Create Date: 2026-08-19 01:32:40.431331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ad6bab5c44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('available_quantity', sa.Integer(), nullable=True))
    op.alter_column(
        'books',
        'available',
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        postgresql_using="available::boolean",
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'available',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('books', 'available_quantity')
    # ### end Alembic commands ###
